// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:1036471a-3ea5-4750-b759-f19af515a56e',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'koalatappawsmobile-hosting-mobilehub-1614086192',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd7m81dor9r4ls.cloudfront.net',
    'aws_mobile_analytics_app_id': 'c4f51b385aac4cd686835786db502ab8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'b630afa9-eac4-4ab7-a933-8c238bb633fa',
    'aws_project_name': 'koalatapp-awsmobile',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'koalatappawsmobile-mobilehub-1614086192',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_k3iNSPOJi',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '30ffloo70g3v5tju36ttue8bqk',
}

export default awsmobile;
