// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    // 'aws_cognito_identity_pool_id': 'us-east-2:905189c1-a431-48eb-b73b-2f970609fabe',
    // 'aws_cognito_region': 'us-east-2',
    // region: 'us-east-2',

    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'koalatappawsmobile-hosting-mobilehub-1614086192',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd7m81dor9r4ls.cloudfront.net',
    'aws_mobile_analytics_app_id': 'c4f51b385aac4cd686835786db502ab8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'b630afa9-eac4-4ab7-a933-8c238bb633fa',
    'aws_project_name': 'koalatapp-awsmobile',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'koalatappawsmobile-mobilehub-1614086192',
    'aws_appsync_graphqlEndpoint': 'https://2iqf5kctojebpejyatpd77ajsa.appsync-api.us-east-2.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-2',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
    'aws_appsync_apiKey': 'da2-m7wtxab4mvdatd55g4x53hlb7u',
    Auth: {
        region: 'us-east-2',
        userPoolId: 'us-east-2_TCxraEfCf',
        userPoolWebClientId: '3bao2pmai9hv2j2g5sdu8dvgc6',
    }
}

export default awsmobile;
